<?php

/**
 * Comments indicate draft status (see <http://www.unicode.org/reports/tr35/#Common_Attributes>).
 * - contributed: partially approved by the technical committee.
 * - provisional: partially confirmed.
 * - unconfirmed: no confirmation available.
 * Language names without comments are fully approved by the technical committee.
 */
$names = array(
'aa' => 'afarština',
'ab' => 'abcházština',
'ace' => 'acehština', #contributed
'ach' => 'ačoli', #contributed
'ada' => 'adangme', #contributed
'ady' => 'adygejština', #contributed
'ae' => 'avestánština', #contributed
'afa' => 'afroasijské jazyky', #contributed
'af' => 'afrikánština',
'afh' => 'afrihili', #contributed
'ain' => 'ainština', #contributed
'ak' => 'akanština', #contributed
'akk' => 'akkadština', #contributed
'ale' => 'aleutština', #contributed
'alg' => 'algonkinské jazyky', #contributed
'am' => 'amharština',
'an' => 'aragonština', #contributed
'ang' => 'staroangličtina', #contributed
'anp' => 'angika', #contributed
'apa' => 'apačské jazyky', #contributed
'ar' => 'arabština',
'arc' => 'aramejština', #contributed
'arn' => 'araukánština', #contributed
'arp' => 'arapažština', #contributed
'art' => 'umělé jazyky', #contributed
'arw' => 'arawacké jazyky', #contributed
'as' => 'asámština',
'ath' => 'athapaskánské jazyky', #contributed
'aus' => 'australské jazyky', #contributed
'av' => 'avarština', #contributed
'awa' => 'awadhština', #contributed
'ay' => 'ajmarština',
'az' => 'ázerbájdžánština',
'ba' => 'baškirština',
'bad' => 'banda', #contributed
'bai' => 'bamilek', #contributed
'bal' => 'balúčština', #contributed
'ban' => 'balijština', #contributed
'bas' => 'basa', #contributed
'bat' => 'baltské jazyky', #contributed
'be' => 'běloruština',
'bej' => 'bedža', #contributed
'bem' => 'bembština', #contributed
'ber' => 'berberské jazyky', #contributed
'bg' => 'bulharština',
'bh' => 'biharština',
'bho' => 'bhojpurština', #contributed
'bi' => 'bislamština',
'bik' => 'bikolština', #contributed
'bin' => 'bini', #contributed
'bla'  => 'siksika', #provisional
'bm' => 'bambarština', #contributed
'bn' => 'bengálština',
'bnt' => 'bantuské jazyky', #contributed
'bo' => 'tibetština',
'bra' => 'bradžština', #contributed
'br' => 'bretaňština',
'bs' => 'bosenština',
'btk' => 'batačtina', #contributed
'bua' => 'burjatština', #contributed
'bug' => 'bugiština', #contributed
'cad' => 'caddo', #contributed
'cai' => 'středoamerické indiánské jazyky', #contributed
'ca' => 'katalánština',
'car' => 'karibština', #contributed
'cau' => 'kavkazské jazyky', #contributed
'ceb' => 'cebuánština', #contributed
'ce' => 'čečenština', #contributed
'cel' => 'keltské jazyky', #contributed
'chb' => 'čibča', #contributed
'ch' => 'čamoro', #contributed
'chg' => 'čagatajština', #contributed
'chk' => 'čukština', #contributed
'chm' => 'marijština', #contributed
'chn' => 'činuk pidžin', #contributed
'cho' => 'čoktština', #contributed
'chp' => 'čipevajština', #contributed
'chr' => 'čerokézština', #contributed
'chy' => 'čejenština', #contributed
'cmc' => 'čamština', #contributed
'co' => 'korsičtina',
'cop' => 'koptština', #contributed
'cpe' => 'anglická kreolština či pidgin', #contributed
'cpf' => 'francouzská kreolština či pidgin', #contributed
'cpp' => 'portugalská kreolština či pidgin', #contributed
'crh' => 'krymská turečtina',
'cr' => 'kríjština', #contributed
'crp' => 'kreolština či pidgin', #contributed
'cs' => 'čeština',
'cus' => 'kúšitské jazyky', #contributed
'cu'  => 'staroslověnština', #provisional
'cv' => 'čuvaština', #contributed
'cy' => 'velština',
'da' => 'dánština',
'dak' => 'dakotština', #contributed
'day' => 'dajáčtina', #contributed
'de-ch' => 'švýcarská standardní němčina', #contributed
'del' => 'delawarština', #contributed
'de' => 'němčina',
'den'  => 'slave', #provisional
'dgr' => 'dogrib', #contributed
'din' => 'dinkština', #contributed
'doi'  => 'dórgí', #provisional
'dra' => 'drávidské jazyky', #contributed
'dua' => 'dualština', #contributed
'dum'  => 'středoholandština', #provisional
'dv' => 'divehi',
'dyu' => 'djula', #contributed
'dz' => 'dzongkä',
'ebu' => 'embu', #contributed
'ee' => 'eweština', #contributed
'efi' => 'efikština',
'egy' => 'egyptština stará', #contributed
'eka' => 'ekajuk', #contributed
'el' => 'řečtina',
'elx' => 'elamitština', #contributed
'en' => 'angličtina',
'en-au' => 'australská angličtina',
'en-ca' => 'anglicky (Kanada)', #contributed
'en-gb' => 'britská angličtina',
'enm'  => 'středoangličtina', #provisional
'en-us' => 'americká angličtina',
'eo' => 'esperanto',
'es' => 'španělština',
'es-419' => 'latinskoamerická španělština',
'es-es' => 'iberská španělština',
'et' => 'estonština',
'eu' => 'baskičtina',
'ewo' => 'ewondo', #contributed
'fan' => 'fang', #contributed
'fa' => 'perština',
'fat' => 'fantština', #contributed
'ff' => 'fulahština', #contributed
'fi' => 'finština',
'fil' => 'filipínština', #contributed
'fiu' => 'ugrofinské jazyky', #contributed
'fj' => 'fidžijština',
'fo' => 'faerština',
'fr' => 'francouzština',
'fr-ch' => 'švýcarská francouzština',
'frm'  => 'středofrancouzština', #provisional
'fro'  => 'starofrancouzština', #provisional
'fur' => 'furlandština', #contributed
'fy' => 'fríština',
'gaa'  => 'ga', #provisional
'ga' => 'irština',
'gay'  => 'gayo', #provisional
'gba'  => 'gbaja', #provisional
'gd' => 'skotská gaelština',
'gem' => 'germánské jazyky', #contributed
'gez'  => 'geez', #provisional
'gil' => 'kiribatština', #contributed
'gl' => 'galicijština',
'gmh' => 'hornoněmčina (středověká)', #contributed
'gn' => 'guaranština',
'goh' => 'hornoněmčina (stará)', #contributed
'gon' => 'góndština', #contributed
'gor' => 'gorontalo', #contributed
'got' => 'gótština', #contributed
'grb' => 'grebo', #contributed
'grc' => 'starořečtina', #contributed
'gsw' => 'němčina (Švýcarsko)',
'gu' => 'gudžarátština',
'gv' => 'manština',
'gwi'  => 'gwichʼin', #provisional
'ha' => 'hauština',
'hai' => 'haidština', #contributed
'haw' => 'havajština', #contributed
'he' => 'hebrejština',
'hi' => 'hindština',
'hil' => 'hiligaynonština', #contributed
'him' => 'himáčalština', #contributed
'hit' => 'chetitština', #contributed
'hmn' => 'hmongština', #contributed
'ho' => 'hiri motu', #contributed
'hr' => 'chorvatština',
'ht' => 'haitština',
'hu' => 'maďarština',
'hup' => 'hupa', #contributed
'hy' => 'arménština',
'hz' => 'hererština', #contributed
'ia' => 'interlingua',
'iba' => 'ibanština', #contributed
'id' => 'indonéština',
'ie' => 'interlingue',
'ig' => 'igboština',
'ijo'  => 'idžo', #provisional
'ik' => 'inupiakština',
'ilo' => 'ilokánština', #contributed
'inc' => 'indické jazyky', #contributed
'ine' => 'indoevropské jazyky', #contributed
'inh' => 'inguština', #contributed
'ira' => 'íránské jazyky', #contributed
'iro' => 'irokézské jazyky', #contributed
'is' => 'islandština',
'it' => 'italština',
'iu' => 'inuktitutština',
'ja' => 'japonština',
'jv' => 'javánština',
'kaa' => 'karakalpačtina', #contributed
'kab' => 'kabylština', #contributed
'kac' => 'kačijština', #contributed
'ka' => 'gruzínština',
'kam' => 'kambština', #contributed
'kar' => 'karenština', #contributed
'kaw' => 'kawi', #contributed
'kbd' => 'kabardinština', #contributed
'kea' => 'kapverdština', #contributed
'kg' => 'konžština', #contributed
'kha' => 'khásí', #contributed
'khi' => 'kojsanské jazyky', #contributed
'kho' => 'chotánština', #contributed
'ki' => 'kikujština', #contributed
'kj' => 'kuaňamština', #contributed
'kk' => 'kazachština',
'kl' => 'grónština',
'kmb'  => 'kimbundština', #provisional
'km' => 'kambodžština',
'kn' => 'kannadština',
'kok' => 'konkánština', #contributed
'ko' => 'korejština',
'kos' => 'kosrajština', #contributed
'kpe'  => 'kpelle', #provisional
'kr'  => 'kanuri', #provisional
'kro'  => 'kru', #provisional
'kru' => 'kuruchština', #contributed
'ks' => 'kašmírština',
'ku' => 'kurdština',
'kum' => 'kumykština', #contributed
'kut'  => 'kutenai', #provisional
'kv'  => 'komijština', #provisional
'kw' => 'kornština', #contributed
'ky' => 'kyrgyzština',
'lad'  => 'ladinština', #provisional
'lah'  => 'lahndština', #provisional
'la' => 'latina',
'lam' => 'lambština', #contributed
'lb' => 'lucemburština',
'lez' => 'lezginština', #contributed
'lg'  => 'ganda', #provisional
'ln' => 'lingalština',
'lo' => 'laoština',
'lol' => 'mongština', #contributed
'loz'  => 'lozština', #provisional
'lt' => 'litevština',
'lua' => 'luba-luluaština', #contributed
'lui' => 'luiseňo', #contributed
'lu' => 'lubu-katanžština', #contributed
'lun' => 'lundština', #contributed
'luo' => 'luoština', #contributed
'lus'  => 'lišáí', #provisional
'luy' => 'luhja', #contributed
'lv' => 'lotyština',
'mad' => 'madurština', #contributed
'mag' => 'magahijština', #contributed
'mai' => 'maithiliština', #contributed
'mak'  => 'makasarština', #provisional
'man'  => 'mandingština', #provisional
'map' => 'austronéské jazyky', #contributed
'mas' => 'masajština', #contributed
'mdr'  => 'mandar', #provisional
'men'  => 'mende', #provisional
'mga'  => 'středoirština', #provisional
'mg' => 'malgaština',
'mh' => 'maršálština', #contributed
'mic'  => 'micmac', #provisional
'mi' => 'maorština',
'min'  => 'minangkabau', #provisional
'mis' => 'různé jazyky', #contributed
'mkh'  => 'mon-khmerské jazyky', #provisional
'mk' => 'makedonština',
'ml' => 'malabarština',
'mnc' => 'mandžuština', #contributed
'mni' => 'manipurština', #contributed
'mn' => 'mongolština',
'mno'  => 'manobo jazyky', #provisional
'moh'  => 'mohawk', #provisional
'mo' => 'moldavština',
'mos'  => 'mosi', #provisional
'mr' => 'maráthština',
'ms' => 'malajština',
'mt' => 'maltština',
'mul'  => 'složené (víceřádkové) jazyky', #provisional
'mun'  => 'mundské jazyky', #provisional
'mus'  => 'muskogee (creek)', #unconfirmed
'mwr'  => 'márvárština', #provisional
'my' => 'barmština',
'myn'  => 'mayské jazyky', #provisional
'nah' => 'nahuatl', #contributed
'nai' => 'severoamerické indiánské jazyky', #contributed
'na' => 'naurština',
'nap'  => 'neapolština', #provisional
'nb' => 'norština (bokmål)',
'nd' => 'ndebele (Zimbabwe)',
'nds'  => 'dolnoněmčina', #provisional
'ne' => 'nepálština',
'new'  => 'névárština', #provisional
'ng'  => 'ndondština', #provisional
'nia'  => 'nias', #provisional
'nic'  => 'nigero-kordofánské jazyky', #provisional
'niu' => 'niueština', #contributed
'nl' => 'nizozemština',
'nl-be' => 'vlámština',
'nn' => 'norština (nynorsk)',
'non'  => 'norština historická', #provisional
'no' => 'norština',
'nr' => 'ndebele (Jižní Afrika)',
'nso' => 'severní sotština',
'nub' => 'núbijské jazyky', #contributed
'nv' => 'navažština', #contributed
'nym' => 'ňamwežština', #contributed
'ny' => 'ňandžština',
'nyn'  => 'nyakolština', #provisional
'nyo'  => 'nyorština', #provisional
'nzi'  => 'nzima', #provisional
'oc' => 'okcitánština',
'oj' => 'odžibvejština', #contributed
'om' => 'oromština (Afan)',
'or' => 'urijština',
'osa'  => 'osage', #provisional
'os' => 'osetština',
'ota' => 'osmanská turečtina', #contributed
'oto'  => 'otomijské jazyky', #provisional
'paa' => 'papuánské jazyky', #contributed
'pag' => 'pangasinanština', #contributed
'pal'  => 'pahlaví', #provisional
'pam'  => 'papangau', #provisional
'pa' => 'paňdžábština',
'pap' => 'papiamento', #contributed
'pau' => 'palauština', #contributed
'peo'  => 'staroperština', #provisional
'phi' => 'filipínské jazyky', #contributed
'phn' => 'féničtina', #contributed
'pi' => 'pálí', #contributed
'pl' => 'polština',
'pon' => 'pohnpeiština', #contributed
'pra' => 'prákrtské jazyky', #contributed
'pro'  => 'provensálština', #provisional
'ps' => 'paštština',
'pt' => 'portugalština',
'pt-br' => 'brazilská portugalština',
'pt-pt' => 'iberská portugalština',
'qu' => 'kečuánština',
'raj' => 'rádžastánština', #contributed
'rap'  => 'rapanuiština', #provisional
'rar' => 'rarotongaština', #contributed
'rm' => 'rétorománština',
'rn' => 'kirundština',
'roa'  => 'románské jazyky', #provisional
'rof' => 'rombo', #contributed
'rom' => 'romština', #contributed
'ro' => 'rumunština',
'ru' => 'ruština',
'rw' => 'kinyarwandština',
'rwk' => 'rwa', #contributed
'sad'  => 'sandawština', #provisional
'sah'  => 'jakutština', #provisional
'sai'  => 'jihoamerické indiánské jazyky', #provisional
'sal' => 'sališské jazyky', #contributed
'sam' => 'samarština', #contributed
'sa' => 'sanskrt',
'sas' => 'sasakština', #contributed
'sat' => 'santálština', #contributed
'sco' => 'skotština', #contributed
'sc' => 'sardština', #contributed
'sd' => 'sindhština',
'sel'  => 'selkupština', #provisional
'sem'  => 'semitské jazyky', #provisional
'se' => 'severní sámština',
'sga'  => 'staroirština', #provisional
'sgn'  => 'znakové jazyky', #provisional
'sg' => 'sangština',
'shn'  => 'šanština', #provisional
'sh' => 'srbochorvatština',
'sid'  => 'sidamo', #provisional
'sio'  => 'siouxské jazyky', #provisional
'si' => 'sinhálština',
'sit' => 'tibetočínské jazyky', #contributed
'sk' => 'slovenština',
'sla' => 'slovanský jazyk', #contributed
'sl' => 'slovinština',
'smi' => 'sámské jazyky', #contributed
'sm' => 'samojština',
'snk'  => 'sonikština', #provisional
'sn' => 'šonština',
'sog'  => 'sogdština', #provisional
'son' => 'songhajština', #contributed
'so' => 'somálština',
'sq' => 'albánština',
'srr' => 'sererština', #contributed
'sr' => 'srbština',
'ssa' => 'nilosaharské jazyky', #contributed
'ss' => 'siswatština',
'st' => 'sesotho',
'suk'  => 'sukuma', #provisional
'sus'  => 'susu', #provisional
'su' => 'sundanština',
'sux' => 'sumerština', #contributed
'sv' => 'švédština',
'swb' => 'komorština', #contributed
'sw' => 'svahilština',
'syr' => 'syrština', #contributed
'tai'  => 'thajské jazyky', #provisional
'ta' => 'tamilština',
'tem'  => 'temne', #provisional
'ter'  => 'tereno', #provisional
'te' => 'telugština',
'tet' => 'tetumština',
'tg' => 'tádžičtina',
'th' => 'thajština',
'tig' => 'tigrejština', #contributed
'ti' => 'tigrinijština',
'tiv'  => 'tivština', #provisional
'tkl' => 'tokelauština', #contributed
'tk' => 'turkmenština',
'tlh' => 'klingonština', #contributed
'tli'  => 'tlingit', #provisional
'tl' => 'tagalog',
'tmh'  => 'tamašek', #provisional
'tn' => 'setswanština',
'to' => 'tonga',
'tpi' => 'tok pisin', #contributed
'tr' => 'turečtina',
'tsi' => 'tsimšijské jazyky', #contributed
'ts' => 'tsonga',
'tt' => 'tatarština',
'tum' => 'tumbukština', #contributed
'tut' => 'altajské jazyky', #contributed
'tvl' => 'tuvalština', #contributed
'tw' => 'twi',
'ty' => 'tahitština', #contributed
'tyv' => 'tuvinština', #contributed
'udm' => 'udmurtština', #contributed
'uga' => 'ugaritština', #contributed
'ug' => 'ujgurština',
'uk' => 'ukrajinština',
'umb'  => 'umbundu', #provisional
'und' => 'neznámý nebo neplatný jazyk',
'ur' => 'urdština',
'uz' => 'uzbečtina',
'vai'  => 'vai', #provisional
've' => 'venda', #contributed
'vi' => 'vietnamština',
'vot'  => 'votiatština', #provisional
'vo' => 'volapuk',
'wae' => 'němčina (walser)', #contributed
'wak' => 'wakašské jazyky', #contributed
'wal' => 'walamština', #contributed
'war'  => 'waray', #provisional
'was' => 'waština', #contributed
'wa' => 'valonština', #contributed
'wen' => 'lužickosrbské jazyky', #contributed
'wo' => 'wolofština',
'xal' => 'kalmyčtina', #contributed
'xh' => 'xhoština',
'yao' => 'jaoština', #contributed
'yap'  => 'yapese', #provisional
'yi' => 'jidiš',
'yo' => 'jorubština',
'ypk'  => 'yupik', #provisional
'yue' => 'kantonština', #contributed
'za' => 'čuangština',
'zap' => 'zapotéčtina', #contributed
'zen'  => 'zenaga', #provisional
'zh' => 'čínština',
'zh-hans' => 'čínština (zjednodušená)',
'znd'  => 'zandština', #provisional
'zun' => 'zunijština', #contributed
'zu' => 'zuluština',
'zxx' => 'žádný jazykový obsah', #contributed
);
